---

- name: Start percona
  service:
    name: mysql
    state: started
  tags:
    - service
    - percona

- name: Stop percona
  service:
    name: mysql
    state: stopped
  tags:
    - service
    - percona

- name: Clean artifact path
  file:
    state: absent
    path: "/var/lib/mysql/"

- name: Change to insecure install to change password
  when: ansible_os_family == 'RedHat'
  shell: "/usr/sbin/mysqld --user=mysql --initialize-insecure --explicit_defaults_for_timestamp"
  args:
    creates: "/var/lib/mysql/mysql"
  tags:
    - config
    - percona
    - skip_ansible_lint

- name: Create first run lock
  file:
    path: /var/lib/mysql/.percona-first-run-done
    state: touch
