---
# handlers file for percona

- name: start mysql
  service:
    name: mysql
    state: started

- name: stop mysql
  service:
    name: mysql
    state: stopped

- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: reload mysql
  service:
    name: mysql
    state: reloaded
